# Utilisation d'une image de base pour PostgreSQL
FROM postgres:13

# Copie d'un script SQL pour initialiser la base de données
COPY init.sql ./

# Exposition du port par défaut pour PostgreSQL
EXPOSE 5432