
CREATE USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';

ALTER DATABASE $POSTGRES_DB OWNER TO $POSTGRES_USER;

-- Connexion à la base de données
\connect $POSTGRES_DB

-- Création de la table "channel"
CREATE TABLE channel (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Création de la table "user"
CREATE TABLE user (
    id SERIAL PRIMARY KEY,
    pseudo VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    status VARCHAR(255) DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);